services:
  communication-backend:
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: mukuflash03/communication-microservice:latest
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
    depends_on:
      - db
    networks:
       - message-network
    deploy:
      restart_policy:
          condition: on-failure

  db:
    image: postgres:16-alpine3.18
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
       - message-network
    ports:
      - "5432:5432"

networks:
  message-network:

volumes:
  postgres_data:
